enable_audio_bell       no
font_family             UbuntuMono Nerd Font
font_size               13.0
bold_font               auto
italic_font             auto
cursor_shape            block
scrollback_lines        10000
window_padding_width    5
enable_ligatures        no
confirm_on_close        no
confirm_os_window_close 0
# special
active_border_color     #edecee
inactive_border_color   #21202e
bell_border_color       #ffca85
url_color               #61ffca

active_tab_foreground   #edecee
active_tab_background   #21202e
inactive_tab_foreground #4d4d4d
inactive_tab_background #21202e

cursor                  #edecee
foreground              #edecee
background              #15141B
selection_foreground    #15141B
selection_background    #edecee

# black
color0                  #1c1b22
color8                  #4d4d4d

# red
color1                  #ff6767
color9                  #ffca85

# green
color2                  #61ffca
color10                 #3aa148

# yellow
color3                  #ffca85
color11                 #ad8a5d

# blue
color4                  #1E90FF
color12                 #175ba0

# magenta
color5                  #a277ff
color13                 #654b9b

# cyan
color6                  #61ffca
color14                 #3fa080

# white
color7                  #edecee
color15                 #edecee